In [1]:
import time
import re
import os
import sys
from bs4 import BeautifulSoup
import requests
from pymongo.errors import ServerSelectionTimeoutError
from pymongo import MongoClient
import random
import json
import pandas as pd
from collections import Counter

client = MongoClient("localhost:27017", serverSelectionTimeoutMS=60)  # 链接mongodb
db_collection = client['专利数据']['人工智能专利_发明授权']

In [60]:
find_db = client['专利数据']['人工智能专利_发明公布']
line = 0
for item in db_collection.find():
    ann_no = item['申请号']
    for item2 in find_db.find({"_id":ann_no}):
        applicated_no = item2['申请公布号']
        db_collection.update_one({"_id":item['_id']},{"$set":{"申请公布号_correct":applicated_no}},upsert=True)
    line += 1
    if line%1000 == 0:
        print(line)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000

In [83]:
all_data = []
line = 47000
for item in db_collection.find().skip(line):
    try:
        applicated_no = item['申请公布号_correct']
        if pd.isna(applicated_no):
            change_no = item['patents_data']['directAssociations'].split("(")[0].strip()
            print(change_no)
            db_collection.update_one({"_id":item['_id']},{"$set":{"申请公布号_correct":change_no}},upsert=True)
    except Exception as e:
        print(e.args, item['_id'])
        change_no = item['patents_data']['applicationNumber'].strip()
        db_collection.update_one({"_id":item['_id']},{"$set":{"申请公布号_correct":change_no}},upsert=True)
        
    if line%1000  == 0:
        print(line)
    line+= 1

47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
('directAssociations',) 038161397
CN102017776A
CN102017779A
CN101808037A
CN102299846A
CN102111342A
CN102196377A
CN102404213A
CN102679935A
CN102640644A
CN102195889A
CN102413062A
CN102571591A
CN1072521A
CN101790740A
CN102037690A
CN102404181A
CN102571539A
CN102401874A
CN102314610A
CN102077521A
CN102480409A
CN102291298A
CN102470274A
CN102377671A
CN102413056A
CN102739527A
CN101502060A
CN102469016A
CN102347906A
CN102325083A
CN101630961A
CN102655477A
CN102474458A
CN102523167A
CN102647363A
CN101632268A
CN102282814A
CN101154281A
CN102571586A
CN102870382A
CN102210126A
CN102244889A
CN102025619A
CN102752207A
CN101997751A
CN102377636A
CN102469022A
CN102577264A
CN102195879A
CN102265698A
CN102356604A
CN102164089A
CN102769572A
CN102047332A
CN102624608A
CN102088390A
CN102724118A
CN102811154A
CN102598599A
CN102831478A
CN101505269A
CN102842318A
CN102695294A
CN102546356A
CN102497316A
CN102474448A
CN102420752A
CN102387465A
CN101309204A
65000
CN102185779A
CN103198363A
CN102394807A
CN102752202A
CN102710327A
CN102308277A
CN102396191A
CN102450076A
CN102567784A
CN102438315A
CN101824948A
CN102598602A
CN102780633A
CN102594652A
CN102142894A
CN102413041A
CN102739555A
CN102129631A
CN102594703A
CN102231713A
CN102710492A
CN101656662A
CN102884763A
CN101277281A
CN102055643A
CN102195868A
CN102474462A
CN102549986A
CN102843744A
CN102480712A
CN102769576A
CN101953224A
CN102832988A
CN103063914A
CN102737362A
CN103051407A
CN102326368A
CN103679371A
CN102819768A
CN102739499A
CN102413052A
CN102779317A
CN102742220A
CN102930903A
CN102420750A
CN102739541A
CN102043366A
CN102342136A
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000

In [52]:
# 获得发明授权的cited by数据

In [3]:
all_data = []
line = 0
for item in db_collection.find():
    try:
        _id,applicated_no,applicated_date, granted_no, granted_date,assignee = item['_id'],item['申请公布号_correct'],item['申请日'],item['授权公告号'],item['授权公告日'],item['专利权人']
        all_data.append({"_id":_id,"applicated_no":applicated_no,"applicated_date":applicated_date, "granted_no":granted_no, "granted_date":granted_date,"assignee":assignee})
    except Exception as e:
        print(e.args, _id)
        break
    if line%1000  == 0:
        print(line)
    line+= 1

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000

In [4]:
result_df = pd.DataFrame(all_data)
result_df

,_id,applicated_no,applicated_date,granted_no,granted_date,assignee
0,2015106287175,CN105260710A,2015.09.28,CN105260710B,2018.08.28,北京石油化工学院
1,2014800261936,CN105229629A,2014.03.05,CN105229629B,2018.10.16,谷歌有限责任公司
2,2014800161228,CN105229667A,2014.03.13,CN105229667B,2017.09.19,艾锐势科技公司
3,2015106733180,CN105260718A,2015.10.13,CN105260718B,2018.07.13,暨南大学
4,2015106003671,CN105260592A,2015.09.18,CN105260592B,2018.08.07,中国地质大学（武汉）
...,...,...,...,...,...,...
127700,2023114115777,CN117152131A,2023.10.30,CN117152131B,2023.12.29,深圳市希格莱特科技有限公司
127701,2023114217855,CN117152148A,2023.10.31,CN117152148B,2023.12.29,南通杰元纺织品有限公司
127702,2023114324255,CN117152157A,2023.10.31,CN117152157B,2023.12.29,南通三喜电子有限公司
127703,2023114450559,CN117173171A,2023.11.02,CN117173171B,2023.12.29,深圳市蓝钛科技有限公司
127704,202311450728X,CN117173180A,2023.11.03,CN117173180B,2023.12.29,江苏康意德科技有限公司

In [6]:
len(result_df['applicated_no'].dropna())

127705

In [8]:
result_df.to_excel("./results/人工智能_异构创新网络专利号_授权号_日期_专利权人.xlsx",index=None)

In [19]:
# 获得cited_by数据

In [9]:
citedby_data = []
line = 0
for item in db_collection.find():
    cited_by = item['cited by']
    
    for i in cited_by:
        i['_id'] = item['_id']
        i['granted_no']=item['授权公告号']
        i['granted_date'] = item['授权公告日']
        i['applicated_no'] = item['申请公布号_correct']
        i['applicated_date'] = item['申请日']
        citedby_data.append(i)
    if line%1000  == 0:
        print(line)
    line+= 1

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000

In [10]:
cb_df = pd.DataFrame(citedby_data)
cb_df

,Publication number,Priority date,Publication date,Assignee,Title,_id,granted_no,granted_date,applicated_no,applicated_date
0,CN105844614B (zh)*,2016-03-15,2019-08-23,广东工业大学,一种基于校对机器人角度的视觉指北方法,2015106287175,CN105260710B,2018.08.28,CN105260710A,2015.09.28
1,CN105868762A (zh)*,2016-03-28,2016-08-17,国网浙江省电力公司宁波供电公司,一种sf6表的读数方法及系统,2015106287175,CN105260710B,2018.08.28,CN105260710A,2015.09.28
2,CN106127204B (zh)*,2016-06-30,2019-08-09,华南理工大学,一种全卷积神经网络的多方向水表读数区域检测算法,2015106287175,CN105260710B,2018.08.28,CN105260710A,2015.09.28
3,CN106228161B (zh)*,2016-07-18,2019-04-19,电子科技大学,一种指针式表盘自动读数方法,2015106287175,CN105260710B,2018.08.28,CN105260710A,2015.09.28
4,CN107220645B (zh)*,2017-05-24,2021-02-26,河北省计量监督检测研究院,基于动态图像处理的水表识别方法,2015106287175,CN105260710B,2018.08.28,CN105260710A,2015.09.28
...,...,...,...,...,...,...,...,...,...,...
1310863,CN117333777B (zh)*,2023-12-01,2024-02-13,山东元明晴技术有限公司,一种坝体异常识别方法、装置及存储介质,202311181886X,CN116912257B,2023.12.29,CN116912257A,2023.09.14
1310864,CN117475806B (zh)*,2023-12-28,2024-03-29,深圳康荣电子有限公司,基于多维传感数据反馈的显示屏自适应响应方法及其装置,2023112434091,CN116985803B,2023.12.29,CN116985803A,2023.09.26
1310865,CN117827466A (zh)*,2024-03-04,2024-04-05,南京宁麒智能计算芯片研究院有限公司,一种多核芯片的动态温度管理方法及系统,2023113308378,CN117074925B,2023.12.29,CN117074925A,2023.10.16
1310866,CN117517932B (zh)*,2023-12-29,2024-03-12,南京邮电大学,一种芯粒间tsv测试电路及测试方法,2023114081889,CN117148117B,2023.12.29,CN117148117A,2023.10.27
1310867,CN117789132B (zh)*,2024-02-27,2024-05-07,深圳市深创高科电子有限公司,基于计算机视觉的电子产品外壳缺陷监测方法及系统,202311450728X,CN117173180B,2023.12.29,CN117173180A,2023.11.03

In [36]:
# cb_df.to_csv("./results/人工智能_异构创新网络_original_cited_by.csv",index=None)

# 对cited_by数据进行处理

In [11]:
# 首先对Publication number进行
cb_df['Publication number_flag'] = cb_df['Publication number'].str.contains("^CN")

In [12]:
flag_1 = cb_df[cb_df['Publication number_flag']==True]
result1 = flag_1.reset_index(drop=True)

In [13]:
result1['Publication_number_pure'] = result1['Publication number'].apply(lambda x: x.split('(')[0].strip())

In [14]:
# 合并专利号数据
patents_no = result_df['applicated_no'].tolist()
patents_no.extend(result_df['granted_no'].tolist())
len(patents_no)

255410

In [15]:
result1['publication_flag'] = result1['Publication_number_pure'].isin(patents_no)

## 判断是否为授权专利引用同一申请专利，如果是则删除

In [16]:
flag_2 = result1[result1['publication_flag']==True]
flag_2 = flag_2.reset_index(drop=True)

In [17]:
flag_2.to_excel("./results/人工智能_异构创新网络_cited_by2.xlsx")

## 判断三、日期问题

In [18]:
flag_2['applicated_date'] = flag_2['applicated_date'].apply(lambda x:x.replace(".","-"))

In [19]:
flag_2['Date1'] = pd.to_datetime(flag_2['applicated_date'], format='%Y-%m-%d')
flag_2['Date2'] = pd.to_datetime(flag_2['Priority date'], format='%Y-%m-%d')

In [20]:
# 计算两列日期之间的差值
flag_2['Date_Diff'] = flag_2['Date2'] - flag_2['Date1']

In [21]:
# 判断日期差值是否为负，并创建一个新列来存储结果
flag_2['date_flag'] = flag_2['Date_Diff'].apply(lambda x: x.days > 0)

In [22]:
result_3 = flag_2[flag_2['date_flag'] == True]
result_3 = result_3.reset_index(drop=True)

In [23]:
result_3.to_excel("./results/人工智能_异构创新网络_cited_by3.xlsx")

# 获得citation数据

In [24]:
citation_data = []
line = 0
for item in db_collection.find():
    citations = item['patent citations']
    
    for i in citations:
        i['_id'] = item['_id']
        i['granted_no']=item['授权公告号']
        i['granted_date'] = item['授权公告日']
        i['applicated_no'] = item['申请公布号_correct']
        i['applicated_date'] = item['申请日']
        citation_data.append(i)
    if line%1000  == 0:
        print(line)
    line+= 1

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000

In [25]:
citation_df = pd.DataFrame(citation_data)

In [34]:
# citation_df.to_csv("./results/人工智能_异构创新网络_original_citation.csv",index=None)

# 对citation数据进行处理

In [26]:
# 首先对Publication number进行
citation_df['Publication number_flag'] = citation_df['Publication number'].str.contains("^CN")

In [27]:
flag_5 = citation_df[citation_df['Publication number_flag']==True]
result5 = flag_5.reset_index(drop=True)

In [28]:
result5['Publication_number_pure'] = result5['Publication number'].apply(lambda x: x.split('(')[0].strip())

In [29]:
# 合并专利号数据
patents_no = result_df['applicated_no'].tolist()
patents_no.extend(result_df['granted_no'].tolist())
len(patents_no)

255410

In [30]:
result5['publication_flag'] = result5['Publication_number_pure'].isin(patents_no)

## 判断是否为授权专利引用同一申请专利，如果是则删除

In [31]:
flag_6 = result5[result5['publication_flag']==True]
flag_6 = flag_6.reset_index(drop=True)

In [41]:
flag_6.to_excel("./results/人工智能_异构创新网络_citation2.xlsx")

## 判断三、日期问题

In [32]:
flag_6['applicated_date'] = flag_6['applicated_date'].apply(lambda x:x.replace(".","-"))

In [33]:
flag_6['Date1'] = pd.to_datetime(flag_6['applicated_date'], format='%Y-%m-%d')
flag_6['Date2'] = pd.to_datetime(flag_6['Priority date'], format='%Y-%m-%d')
# 计算两列日期之间的差值
flag_6['Date_Diff'] = flag_6['Date2'] - flag_6['Date1']

# 判断日期差值是否为负，并创建一个新列来存储结果
flag_6['date_flag'] = flag_6['Date_Diff'].apply(lambda x: x.days <= 0)

result_7 = flag_6[flag_6['date_flag'] == True]
result_7 = result_7.reset_index(drop=True)

In [34]:
result_7.to_excel("./results/人工智能_异构创新网络_citation3.xlsx")

# 处理temp_data数据

In [36]:
read_data = pd.read_excel("./results/temp_data.xlsx")
read_data

,citing_no,citing_date,citing_assignee,cited_no,cited_date,cited_assignee,citing_cited
0,CN105844614B,2016-03-15,广东工业大学,CN105260710B,2015-09-28,北京石油化工学院,CN105844614B_CN105260710B
1,CN112214368B,2020-10-23,英业达科技有限公司;英业达股份有限公司,CN105224430B,2015-10-29,艾德克斯电子（南京）有限公司,CN112214368B_CN105224430B
2,CN112910720B,2021-05-06,成都云智天下科技股份有限公司,CN105245362B,2015-09-14,河南工业大学; 西安电子科技大学,CN112910720B_CN105245362B
3,CN104608125B,2013-11-01,精工爱普生株式会社,CN105234938B,2011-07-11,精工爱普生株式会社,CN104608125B_CN105234938B
4,CN106239505B,2016-08-01,广东电网有限责任公司电力科学研究院,CN105234938B,2011-07-11,精工爱普生株式会社,CN106239505B_CN105234938B
...,...,...,...,...,...,...,...
154534,CN117152131B,2023-10-30,深圳市希格莱特科技有限公司,CN116862907A,2023-08-30,无锡市明通动力工业有限公司,CN117152131B_CN116862907A
154535,CN117152148B,2023-10-31,南通杰元纺织品有限公司,CN114757900A,2022-03-31,绍兴柯桥奇诺家纺用品有限公司,CN117152148B_CN114757900A
154536,CN117152148B,2023-10-31,南通杰元纺织品有限公司,CN115082466A,2022-08-22,倍利得电子科技（深圳）有限公司,CN117152148B_CN115082466A
154537,CN117152157B,2023-10-31,南通三喜电子有限公司,CN112862770A,2021-01-29,珠海迪沃航空工程有限公司,CN117152157B_CN112862770A
154538,CN117173171B,2023-11-02,深圳市蓝钛科技有限公司,CN108682012A,2018-05-15,佛山市南海区广工大数控装备协同创新研究院;佛山市广工大数控装备技术发展有限公司,CN117173171B_CN108682012A

In [39]:
read_data['citing_assignee_pure'] = read_data['citing_assignee'].apply(lambda x:x.replace("全部","").replace("\n","").replace(" ","").strip())

In [40]:
read_data['cited_assignee_pure'] = read_data['cited_assignee'].apply(lambda x:x.replace("全部","").replace("\n","").replace(" ","").strip())

In [45]:
read_data['citing_count'] = read_data['citing_cited'].value_counts()

In [52]:
df = pd.DataFrame(read_data['citing_cited'].value_counts())
new_df = df.reset_index()
new_df

                     citing_cited  count
0       CN113997292B_CN110355754B      2
1       CN111337895B_CN107462877B      2
2       CN113907707B_CN112353368B      2
3       CN112348806B_CN111783494B      2
4       CN109147940B_CN106815566B      2
...                           ...    ...
153818   CN101382888B_CN100570556      1
153819   CN103823686B_CN100570556      1
153820   CN101751258B_CN100543674      1
153821   CN101937354B_CN100543674      1
153822  CN117173171B_CN108682012A      1

[153823 rows x 2 columns]

In [53]:
final_df = pd.merge(read_data,new_df,on='citing_cited')
final_df

,citing_no,citing_date,citing_assignee,cited_no,cited_date,cited_assignee,citing_cited,citing_assignee_pure,cited_assignee_pure,citing_count,count
0,CN105844614B,2016-03-15,广东工业大学,CN105260710B,2015-09-28,北京石油化工学院,CN105844614B_CN105260710B,广东工业大学,北京石油化工学院,NaN,1
1,CN112214368B,2020-10-23,英业达科技有限公司;英业达股份有限公司,CN105224430B,2015-10-29,艾德克斯电子（南京）有限公司,CN112214368B_CN105224430B,英业达科技有限公司;英业达股份有限公司,艾德克斯电子（南京）有限公司,NaN,1
2,CN112910720B,2021-05-06,成都云智天下科技股份有限公司,CN105245362B,2015-09-14,河南工业大学; 西安电子科技大学,CN112910720B_CN105245362B,成都云智天下科技股份有限公司,河南工业大学; 西安电子科技大学,NaN,1
3,CN104608125B,2013-11-01,精工爱普生株式会社,CN105234938B,2011-07-11,精工爱普生株式会社,CN104608125B_CN105234938B,精工爱普生株式会社,精工爱普生株式会社,NaN,1
4,CN106239505B,2016-08-01,广东电网有限责任公司电力科学研究院,CN105234938B,2011-07-11,精工爱普生株式会社,CN106239505B_CN105234938B,广东电网有限责任公司电力科学研究院,精工爱普生株式会社,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
154534,CN117152131B,2023-10-30,深圳市希格莱特科技有限公司,CN116862907A,2023-08-30,无锡市明通动力工业有限公司,CN117152131B_CN116862907A,深圳市希格莱特科技有限公司,无锡市明通动力工业有限公司,NaN,1
154535,CN117152148B,2023-10-31,南通杰元纺织品有限公司,CN114757900A,2022-03-31,绍兴柯桥奇诺家纺用品有限公司,CN117152148B_CN114757900A,南通杰元纺织品有限公司,绍兴柯桥奇诺家纺用品有限公司,NaN,1
154536,CN117152148B,2023-10-31,南通杰元纺织品有限公司,CN115082466A,2022-08-22,倍利得电子科技（深圳）有限公司,CN117152148B_CN115082466A,南通杰元纺织品有限公司,倍利得电子科技（深圳）有限公司,NaN,1
154537,CN117152157B,2023-10-31,南通三喜电子有限公司,CN112862770A,2021-01-29,珠海迪沃航空工程有限公司,CN117152157B_CN112862770A,南通三喜电子有限公司,珠海迪沃航空工程有限公司,NaN,1
154538,CN117173171B,2023-11-02,深圳市蓝钛科技有限公司,CN108682012A,2018-05-15,佛山市南海区广工大数控装备协同创新研究院;佛山市广工大数控装备技术发展有限公司,CN117173171B_CN108682012A,深圳市蓝钛科技有限公司,佛山市南海区广工大数控装备协同创新研究院;佛山市广工大数控装备技术发展有限公司,NaN,1

In [54]:
final_df.to_excel("./results/result_temp_data.xlsx",index=None)

# 将曾用名改为现用名

In [63]:
read_data = pd.read_excel("./results/result_temp_data.xlsx",sheet_name=0)
cym_data = pd.read_excel("./results/result_temp_data.xlsx", sheet_name=7)

In [56]:
read_data

,citing_no,citing_date,citing_assignee,cited_no,cited_date,cited_assignee_pure,citing_cited
0,CN105844614B,2016-03-15,广东工业大学,CN105260710B,2015-09-28,北京石油化工学院,CN105844614B_CN105260710B
1,CN112214368B,2020-10-23,英业达科技有限公司;英业达股份有限公司,CN105224430B,2015-10-29,艾德克斯电子（南京）有限公司,CN112214368B_CN105224430B
2,CN112910720B,2021-05-06,成都云智天下科技股份有限公司,CN105245362B,2015-09-14,河南工业大学; 西安电子科技大学,CN112910720B_CN105245362B
3,CN104608125B,2013-11-01,精工爱普生株式会社,CN105234938B,2011-07-11,精工爱普生株式会社,CN104608125B_CN105234938B
4,CN106239505B,2016-08-01,广东电网有限责任公司电力科学研究院,CN105234938B,2011-07-11,精工爱普生株式会社,CN106239505B_CN105234938B
...,...,...,...,...,...,...,...
153818,CN113205509B,2021-05-24,山东省人工智能研究院;齐鲁工业大学,CN111709925B,2020-06-11,深圳科亚医疗科技有限公司,CN113205509B_CN111709925B
153819,CN115272165B,2022-05-10,推想医疗科技股份有限公司,CN111709925B,2020-06-11,深圳科亚医疗科技有限公司,CN115272165B_CN111709925B
153820,CN115222665B,2022-06-13,北京医准智能科技有限公司,CN111709925B,2020-06-11,深圳科亚医疗科技有限公司,CN115222665B_CN111709925B
153821,CN110596328B,2019-06-25,北京机械设备研究所,CN107449874B,2017-09-13,中国科学院地理科学与资源研究所,CN110596328B_CN107449874B
153822,CN110355755B,2018-12-15,深圳铭杰医疗科技有限公司,CN107127755B,2017-05-12,华南理工大学,CN110355755B_CN107127755B

In [62]:
key_value = dict(zip(cym_data["citing_assignee"],cym_data['现用名']))
key_value

{'浙江科技学院': '浙江科技大学',
 '郑州轻工业学院': '郑州轻工业大学',
 '浙江大学城市学院': '浙大城市学院',
 '浙江大学宁波理工学院': '浙大宁波理工学院',
 '江西理工大学应用科学学院': '赣南科技学院',
 '温州大学瓯江学院': '温州理工学院',
 '华南理工大学广州学院': '广州城市理工学院',
 '中国计量学院': '中国计量大学',
 '广东技术师范学院': '广东技术师范大学',
 '广西师范学院': '南宁师范大学',
 '中州大学': '郑州工程技术学院',
 '安庆师范学院': '安庆师范大学',
 '四川理工学院': '四川轻化工大学',
 '南京化工职业技术学院': '南京科技职业学院',
 '西安财经学院': '西安财经大学',
 '淮海工学院': '江苏海洋大学',
 '苏州科技学院': '苏州科技大学',
 '大连民族学院': '大连民族大学',
 '河南中医学院': '河南中医药大学',
 '阜阳师范学院': '阜阳师范大学',
 '陕西理工学院': '陕西理工大学',
 '温州医学院眼视光研究院': '温州医科大学眼视光研究院',
 '广东商学院': '广东财经大学',
 '中国人民解放军西安通信学院': '中国人民解放军国防科技大学西安通信学院',
 '淮安信息职业技术学院': '江苏电子信息职业学院',
 '阿坝师范高等专科学校': '阿坝师范学院',
 '承德石油高等专科学校': '河北石油职业技术大学',
 '江西科技师范学院': '江西科技师范大学',
 '重庆工学院': '重庆理工大学',
 '成都信息工程学院': '成都信息工程大学',
 '南京邮电学院': '南京邮电大学',
 '中国人民解放军装甲兵技术学院': '中国人民解放军陆军装甲兵学院',
 '浙江海洋学院': '浙江海洋大学',
 '上海应用技术学院': '上海应用技术大学',
 '北京建筑工程学院': '北京建筑大学',
 '中国人民武装警察部队学院': '中国人民警察大学',
 '柳州师范高等专科学校': '广西科技师范学院',
 '广西工学院': '广西科技大学',
 '华北水利水电学院': '华北水利水电大学',
 '徐州师范大学': '江苏师范大学',
 '西安邮电学院': '西安邮电大学',
 '浙江林学院': '浙江农林大学',
 '山东轻工业学院': '齐鲁工业大学',
 '沈阳化工学院': '沈阳化工大学',
 '重庆邮电学院': '重庆邮电大学',
 '广西科技大学鹿山学院': '柳州工学院',
 '吉林大学珠海学院': '珠海科技学院',
 '四川大学锦城学院': '成都锦城学院',
 '国网江苏省电力公司电力科学研究院': '国网江苏省电力有限公司电力科学研究院',
 '北京卫星制造厂': '北京卫星制造厂有限公司',
 '钢铁研究总院': '钢铁研究总院有限公司',
 '武汉邮电科学研究院': '武汉邮电科学研究院有限公司',
 '中国电力科学研究院': '中国电力科学研究院有限公司',
 '四川省建筑设计研究院': '四川省建筑设计研究院有限公司',
 '中国铁道科学研究院电子计算技术研究所': '中国铁道科学研究院集团有限公司电子计算技术研究所',
 '电信科学技术研究院': '电信科学技术研究院有限公司',
 '广东电网公司电力科学研究院': '广东电网有限责任公司电力科学研究院',
 '贵州省矿山安全科学研究院': '贵州省矿山安全科学研究院有限公司',
 '广西电网公司电力科学研究院': '广西电网有限责任公司电力科学研究院',
 '北京市新技术应用研究所': '北京市新技术应用研究所有限公司',
 '中国食品发酵工业研究院': '中国食品发酵工业研究院有限公司',
 '上海材料研究所': '上海材料研究所有限公司',
 '中国大唐集团科学技术研究院有限公司西北电力试验研究院': '中国大唐集团科学技术研究总院有限公司西北电力试验研究院',
 '云南电网公司电力科学研究院': '云南电网有限责任公司电力科学研究院',
 '广东电网公司电网规划研究中心': '广东电网有限责任公司电网规划研究中心',
 '国网电力科学研究院': '国网电力科学研究院有限公司',
 '贵州电网公司电力调度控制中心': '贵州电网有限责任公司电力调度控制中心',
 '国网安徽省电力公司经济技术研究院': '国网安徽省电力有限公司经济技术研究院',
 '华电电力科学研究院': '华电电力科学研究院有限公司',
 '北京市计算中心': '北京市计算中心有限公司',
 '甘肃省电力公司电力科学研究院': '国网甘肃省电力公司电力科学研究院',
 '四川电力科学研究院': '国网四川省电力公司电力科学研究院',
 '广东电网公司电力调度控制中心': '广东电网有限责任公司电力调度控制中心',
 '广东电网公司信息中心': '广东电网有限责任公司信息中心',
 '冶金自动化研究设计院': '冶金自动化研究设计院有限公司',
 '北京有色金属研究总院': '北京有色金属研究总院有限公司',
 '中国石油化工股份有限公司胜利油田分公司西部新区研究院': '中国石油化工股份有限公司胜利油田分公司勘探开发研究院西部分院',
 '中国铁道科学研究院': '中国铁道科学研究院集团有限公司',
 '电信科学技术仪表研究所': '电信科学技术仪表研究所有限公司',
 '国网安徽省电力公司电力科学研究院': '国网安徽省电力有限公司电力科学研究院',
 '上海市建筑科学研究院': '上海市建筑科学研究院有限公司',
 '中国农业机械化科学研究院': '中国农业机械化科学研究院集团有限公司',
 '北京自动测试技术研究所': '北京自动测试技术研究所有限公司',
 '冀北电力有限公司电力经济技术研究院': '国网冀北电力有限公司经济技术研究院',
 '国网宁夏电力公司电力科学研究院': '国网宁夏电力有限公司电力科学研究院',
 '贵州电力试验研究院': '贵州电网有限责任公司电力科学研究院',
 '国网能源研究院': '国网能源研究院有限公司',
 '重庆市电力公司电力科学研究院': '国网重庆市电力公司电力科学研究院',
 '广州医科大学附属第一医院': '广州医科大学附属第一医院（广州呼吸中心）',
 '贵州电网公司电网规划研究中心': '贵州电网有限责任公司电网规划研究中心',
 '中国能源建设集团广东省电力设计研究院': '中国能源建设集团广东省电力设计研究院有限公司',
 '上海邮政科学研究院': '上海邮政科学研究院有限公司',
 '北京矿冶研究总院': '北京矿冶研究总院有限公司',
 '中国铁道科学研究院铁道建筑研究所': '中国铁道科学研究院集团有限公司铁道建筑研究所',
 '国电环境保护研究院': '国电环境保护研究院有限公司',
 '甘肃省电力公司风电技术中心': '国网甘肃省电力公司风电技术中心',
 '南京南瑞集团公司北京监控技术中心': '南瑞集团有限公司北京监控技术中心',
 '国网湖南省电力公司电力科学研究院': '国网湖南省电力有限公司电力科学研究院',
 '国网湖南省电力公司防灾减灾中心': '国网湖南省电力有限公司防灾减灾中心',
 '国网计量中心': '国网计量中心有限公司',
 '北京电力经济技术研究院': '北京电力经济技术研究院有限公司',
 '煤炭科学研究总院': '煤炭科学研究总院有限公司',
 '国网北京经济技术研究院': '国网经济技术研究院有限公司',
 '福建省电力有限公司电力科学研究院': '国网福建省电力有限公司电力科学研究院',
 '黑龙江省电力科学研究院': '国网黑龙江省电力有限公司电力科学研究院',
 '国网湖北省电力公司经济技术研究院': '国网湖北省电力有限公司经济技术研究院',
 '华能集团技术创新中心': '华能集团技术创新中心有限公司',
 '中国石油化工股份有限公司胜利油田分公司地质科学研究院': '中国石油化工股份有限公司胜利油田分公司勘探开发研究院',
 '国网浙江省电力公司经济技术研究院': '国网浙江省电力有限公司经济技术研究院',
 '国网湖北省电力公司电力科学研究院': '国网湖北省电力有限公司电力科学研究院',
 '中海油研究总院': '中海油研究总院有限责任公司',
 '国网浙江省电力公司电力科学研究院': '国网浙江省电力有限公司电力科学研究院',
 '国网河北省电力公司电力科学研究院': '国网河北省电力有限公司电力科学研究院',
 '山西省电力公司电力科学研究院': '国网山西省电力公司电力科学研究院',
 '中国铁道科学研究院通信信号研究所': '中国铁道科学研究院集团有限公司通信信号研究所',
 '国网新疆电力公司电力科学研究院': '国网新疆电力有限公司电力科学研究院',
 '广东欧珀移动通信有限公司': 'OPPO广东移动通信有限公司',
 '北京红马传媒文化发展有限公司': '北京大麦文化传媒发展有限公司',
 '维沃移动通信有限公司': '艾酷电子科技有限公司',
 '深圳市华讯方舟太赫兹科技有限公司': '深圳市重投华讯太赫兹科技有限公司',
 '长光卫星技术有限公司': '长光卫星技术股份有限公司',
 '深圳和而泰数据资源与云技术有限公司': '深圳和而泰智能家电控制器有限公司',
 '罗普特（厦门）科技集团有限公司': '罗普特科技集团股份有限公司',
 '成都卡诺普自动化控制技术有限公司': '成都卡诺普机器人技术股份有限公司',
 '珠海市一微半导体有限公司': '珠海一微半导体股份有限公司',
 '深圳蓝胖子机器人有限公司': '深圳蓝胖子机器智能有限公司',
 '深圳云天励飞技术有限公司': '深圳云天励飞技术股份有限公司',
 '海门市博洋铸造有限公司': '南通市博洋铸造有限公司',
 '武汉万集信息技术有限公司': '武汉万集光电技术有限公司',
 '深圳市优必选科技有限公司': '深圳市优必选科技股份有限公司',
 '达闼机器人有限公司': '达闼机器人股份有限公司',
 '广州杰赛科技股份有限公司': '中电科普天科技股份有限公司',
 '天津中科智能识别产业技术研究院有限公司': '天津中科智能识别有限公司',
 '南京壹进制信息科技有限公司': '航天壹进制（江苏）信息科技有限公司',
 '深圳市越疆科技有限公司': '深圳市越疆科技股份有限公司',
 '京信通信系统（中国）有限公司': '京信网络系统股份有限公司',
 '深圳市奔凯安全技术股份有限公司': '深圳市奔凯信息服务集团股份有限公司',
 '深圳市海清视讯科技有限公司': '深圳海清智元科技股份有限公司',
 '湘电风能有限公司': '湖南兴蓝风电有限公司',
 '浙江零跑科技有限公司': '浙江零跑科技股份有限公司',
 '安徽华米智能科技有限公司': '安徽华米健康科技有限公司',
 '合肥欣奕华智能机器有限公司': '合肥欣奕华智能机器股份有限公司',
 '国网江苏省电力公司常州供电公司': '国网江苏省电力有限公司常州供电分公司',
 '辽宁奇辉电子系统工程有限公司': '辽宁鼎汉奇辉电子系统工程有限公司',
 '国网江苏省电力公司无锡供电公司': '国网江苏省电力有限公司无锡供电分公司',
 '深圳奥比中光科技有限公司': '奥比中光科技集团股份有限公司',
 '深圳市飘飘宝贝有限公司': '深圳市六六六网络服务有限公司',
 '北京至真互联网技术有限公司': '北京至真健康科技有限公司',
 '厦门歌乐电子企业有限公司': '佛吉亚歌乐电子（厦门）有限公司',
 '中标慧安信息技术股份有限公司': '慧之安信息技术股份有限公司',
 '厦门中控智慧信息技术有限公司': '厦门熵基科技有限公司',
 '北京云迹科技有限公司': '北京云迹科技股份有限公司',
 '深圳乐动机器人有限公司': '深圳乐动机器人股份有限公司',
 '西安奕斯伟材料科技有限公司': '西安奕斯伟材料科技股份有限公司',
 '福建兴宇信息科技有限公司': '福州恒态信息科技有限公司',
 '成都科来软件有限公司': '成都数默科技有限公司',
 '贵州白山云科技有限公司': '贵州白山云科技股份有限公司',
 '东莞先知大数据有限公司': '广东先知大数据股份有限公司',
 '深圳市大族数控科技有限公司': '深圳市大族数控科技股份有限公司',
 '高视科技（苏州）有限公司': '高视科技（苏州）股份有限公司',
 '蔚来（安徽）控股有限公司': '蔚来控股有限公司',
 'TCL集团股份有限公司': 'TCL科技集团股份有限公司',
 '郑州宇通客车股份有限公司': '宇通客车股份有限公司',
 '上海节卡机器人科技有限公司': '节卡机器人股份有限公司',
 '昆山塔米机器人有限公司': '苏州塔米机器人有限公司',
 '东方红卫星移动通信有限公司': '中国星网网络应用有限公司',
 '易思维（杭州）科技有限公司': '易思维（杭州）科技股份有限公司',
 '南京甄视智能科技有限公司': '小视科技（江苏）股份有限公司',
 '深圳市银星智能科技股份有限公司': '深圳银星智能集团股份有限公司',
 '数坤（北京）网络科技股份有限公司': '数坤科技股份有限公司',
 '山东中车风电有限公司': '中车山东风电有限公司',
 '宜人恒业科技发展（北京）有限公司': '优赛恒创科技发展（北京）有限公司',
 '北京智行者科技有限公司': '北京智行者科技股份有限公司',
 '江西高创保安服务技术有限公司': '高创安邦（江西）技术有限公司',
 '中控智慧科技股份有限公司': '熵基科技股份有限公司',
 '北京握奇数据系统有限公司': '北京握奇数据股份有限公司',
 '武大吉奥信息技术有限公司': '吉奥时空信息技术股份有限公司',
 '惠州市华星光电技术有限公司': '惠州华星光电显示有限公司',
 '成都深思科技有限公司': '成都锋卫科技有限公司',
 '苏州博众机器人有限公司': '苏州博众智能机器人有限公司',
 '北京优锘科技有限公司': '北京优锘科技股份有限公司',
 '上海海栎创微电子有限公司': '上海海栎创科技股份有限公司',
 '中策橡胶集团有限公司': '中策橡胶集团股份有限公司',
 '浙江想能云软件股份有限公司': '嘉兴想能云软件有限公司',
 '无锡北邮感知技术产业研究院有限公司': '北邮感知技术研究院（江苏）有限公司',
 '象辑科技（武汉）股份有限公司': '象辑科技股份有限公司',
 '深圳市岑科实业有限公司': '岑科科技（深圳）集团有限公司',
 '深圳市道通智能航空技术有限公司': '深圳市道通智能航空技术股份有限公司',
 '速眠创新科技（深圳）有限公司': '柏斯速眠科技（深圳）有限公司',
 '厦门靠谱云股份有限公司': '福建靠谱云算力技术有限公司',
 '万兴科技股份有限公司': '万兴科技集团股份有限公司',
 '四川锦江电子科技有限公司': '四川锦江电子医疗器械科技股份有限公司',
 '普瑞达建设有限公司': '普瑞达科技集团有限公司',
 '国网福建省电力有限公司': '福建省电力有限公司',
 '深圳市斯尔顿科技有限公司': '深圳莫廷医疗科技有限公司',
 '国网湖北省电力公司': '国网湖北省电力有限公司',
 '上海和辉光电有限公司': '上海和辉光电股份有限公司',
 '广州极飞科技有限公司': '广州极飞科技股份有限公司',
 '广东信佰君略科技咨询有限公司': '广东君略科技咨询有限公司',
 '盛科网络（苏州）有限公司': '苏州盛科通信股份有限公司',
 '深圳市华星光电技术有限公司': 'TCL华星光电技术有限公司',
 '中国华能集团公司': '中国华能集团有限公司',
 '北京海博思创科技有限公司': '北京海博思创科技股份有限公司',
 '深圳配天智能技术研究院有限公司': '深圳配天机器人技术有限公司',
 '广东兆邦智能科技有限公司': '广东兆邦智能科技股份有限公司',
 '国网江苏省电力公司南京供电公司': '国网江苏省电力有限公司南京供电分公司',
 '北京推想科技有限公司': '推想医疗科技股份有限公司',
 '东莞市三姆森光电科技有限公司': '广东三姆森科技股份有限公司',
 '南京华科和鼎信息科技有限公司': '武汉华科和鼎信息科技有限公司',
 '深圳市奇虎智能科技有限公司': '深圳市三六零智慧生活科技有限公司',
 '北京智慧眼科技股份有限公司': '智慧眼科技股份有限公司',
 '银江股份有限公司': '银江技术股份有限公司',
 '威马智慧出行科技（上海）有限公司': '威马智慧出行科技（上海）股份有限公司',
 '沈阳黎明航空发动机（集团）有限责任公司': '中国航发沈阳黎明航空发动机有限责任公司',
 '北京极智嘉科技有限公司': '北京极智嘉科技股份有限公司',
 '华为机器有限公司': '聚信科技有限公司',
 '上海矽久微电子有限公司': '宁波矽久微电子有限公司',
 '国信优易数据有限公司': '国信优易数据股份有限公司',
 '安徽四创电子股份有限公司': '四创电子股份有限公司',
 '青岛海信移动通信技术股份有限公司': '青岛海信移动通信技术有限公司',
 '全球能源互联网研究院有限公司': '国网智能电网研究院有限公司',
 '成都国星宇航科技有限公司': '成都国星宇航科技股份有限公司',
 '北京万里红科技股份有限公司': '北京万里红科技有限公司',
 '佳都新太科技股份有限公司': '佳都科技集团股份有限公司',
 '盘锦辽河油田泰利达顺诚环保工程有限公司': '盘锦辽河油田顺诚生态环保工程有限公司',
 '北京京深深向科技有限公司': '安徽深向科技有限公司',
 '深圳米飞泰克科技有限公司': '深圳米飞泰克科技股份有限公司',
 '成都数之联科技有限公司': '成都数之联科技股份有限公司',
 '济南翼菲自动化科技有限公司': '济南翼菲智能科技股份有限公司',
 '硅谷数模（苏州）半导体有限公司': '硅谷数模（苏州）半导体股份有限公司',
 '艾普柯微电子（上海）有限公司': '艾普柯微电子（江苏）有限公司',
 '沈阳高精数控智能技术股份有限公司': '沈阳中科数控技术股份有限公司',
 '北京青藤文化股份有限公司': '北京青藤科技股份有限公司',
 '广东宏恩健康管理集团股份有限公司': '广东宏恩健康管理科技集团股份有限公司',
 '北京航天宏图信息技术股份有限公司': '航天宏图信息技术股份有限公司',
 '北京佰才邦技术有限公司': '北京佰才邦技术股份有限公司',
 '上海联影医疗科技有限公司': '上海联影医疗科技股份有限公司',
 '深圳前海达闼云端智能科技有限公司': '深圳达闼云端智能科技有限公司',
 '遨博（北京）智能科技有限公司': '遨博（北京）智能科技股份有限公司',
 '四川世纪云道科技有限公司': '四川来吖科技有限公司',
 '上海小蚁科技有限公司': '云蚁智联（上海）信息技术有限公司',
 '中科星图（西安）测控技术有限公司': '中科星图测控技术股份有限公司',
 '上海优医基医疗影像设备有限公司': '上海竞植实业发展有限公司',
 '航天星图科技（北京）有限公司': '中科星图股份有限公司',
 '武汉资联虹康科技股份有限公司': '武汉资联虹康科技有限公司',
 '广东电力信息科技有限公司': '南方电网数字企业科技（广东）有限公司',
 '湖南长城信息金融设备有限责任公司': '长城信息股份有限公司',
 '重庆市智权之路科技有限公司': '重庆真逆思维科技有限公司',
 '上海创景信息科技有限公司': '上海创景信息科技股份有限公司',
 '国家电网公司': '国家电网有限公司',
 '沈阳熙康阿尔卑斯科技有限公司': '东软熙康阿尔卑斯（沈阳）科技有限公司',
 '广东普标技术研究有限公司': '广州广微计量检测技术有限公司',
 '青岛义龙包装机械有限公司': '青岛义龙装备制造股份有限公司',
 '江苏易图地理信息科技股份有限公司': '江苏易图地理信息科技有限公司',
 '中通客车控股股份有限公司': '中通客车股份有限公司',
 '杭州华三通信技术有限公司': '新华三技术有限公司',
 '北京普莱德新能源电池科技有限公司': '北京和中普方新能源科技有限公司',
 '武汉光庭科技有限公司': '武汉光昱明晟智能科技有限公司',
 '深圳市普汇智联科技有限公司': '深圳市奇德宝科技有限公司',
 '浪潮云信息技术有限公司': '浪潮云信息技术股份公司',
 '重庆中科云丛科技有限公司': '重庆中科云从科技有限公司',
 '南京凌深信息科技有限公司': '南京凌深智能科技研究院有限公司',
 '安徽江淮汽车股份有限公司': '安徽江淮汽车集团股份有限公司',
 '奇瑞新能源汽车技术有限公司': '奇瑞新能源汽车股份有限公司',
 '山西圣点世纪科技股份有限公司': '圣点世纪科技股份有限公司',
 '长春通视光电技术有限公司': '长春通视光电技术股份有限公司',
 '华为终端有限公司': '华为终端（深圳）有限公司',
 '深圳市爱协生科技有限公司': '深圳市爱协生科技股份有限公司',
 '飞亚达（集团）股份有限公司': '飞亚达精密科技股份有限公司',
 '合一网络技术（北京）有限公司': '优酷网络技术（北京）有限公司',
 '青岛海信电器股份有限公司': '海信视像科技股份有限公司',
 '广州明珞汽车装备有限公司': '广州明珞装备股份有限公司',
 '国网电子商务有限公司': '国网数字科技控股有限公司',
 '南京凯瑞得信息科技有限公司': '凯睿星通信息科技（南京）股份有限公司',
 '中国移动通信集团公司': '中国移动通信集团有限公司',
 '武汉四通信息服务有限公司': '武汉吧哒科技股份有限公司',
 '上海智驾汽车科技有限公司': '智驾汽车科技（宁波）有限公司',
 '中科亿和智慧物联（深圳）有限公司': '中科爱芯微环境信息科技（深圳）有限公司',
 '绍兴市寅源智能科技有限公司': '绍兴市侨陆智能科技有限公司',
 '福建星网锐捷网络有限公司': '锐捷网络股份有限公司',
 '成都火云网安科技有限公司': '成都千牛企业管理有限公司',
 '江苏鸿信系统集成有限公司': '中电鸿信信息科技有限公司',
 '北京华检智研软件技术有限责任公司': '北京佰优电子商务有限公司',
 '深圳市寒武纪智能科技有限公司': '苏悦寒武纪（江苏）科技有限公司',
 '东莞市七宝树教育科技有限公司': '东莞茅飞信息科技有限公司',
 '江西欧迈斯微电子有限公司': '欧菲微电子（南昌）有限公司',
 '恒大法拉第未来智能汽车（广东）有限公司': '恒大智能汽车（广东）有限公司',
 '北京郁金香伙伴科技有限公司': '北京鹰瞳科技发展股份有限公司',
 '国网浙江省电力公司信息通信分公司': '国网浙江省电力有限公司信息通信分公司',
 '司马大大（北京）智能系统有限公司': '司马达拓（深圳）智能系统有限公司',
 '苏宁易购集团股份有限公司': '遵义市大丰农作物研究所',
 '国睿集团有限公司': '中电国睿集团有限公司',
 '深圳市多彩人生技术有限公司': '深圳市多彩人生技术股份有限公司',
 '深圳市南方众悦供应链有限公司': '深圳市南方众悦科技有限公司',
 '浙江华睿科技有限公司': '浙江华睿科技股份有限公司',
 '浙江维尔科技股份有限公司': '浙江维尔科技有限公司',
 '高拓讯达（北京）科技有限公司': '高拓讯达（北京）微电子股份有限公司',
 '北京华峰测控技术有限公司': '北京华峰测控技术股份有限公司',
 '武汉烽火众智数字技术有限责任公司': '武汉众智数字技术有限公司',
 '广东浪潮大数据研究有限公司': '广东浪潮智慧计算技术有限公司',
 '重庆七腾科技有限公司': '七腾机器人有限公司',
 '江苏正金建筑装饰工程有限公司': '正金装饰集团有限公司',
 '深圳前海联动云软件科技有限公司': '深圳联动易行科技有限公司',
 '北京医准智能科技有限公司': '浙江医准智能科技有限公司',
 '杭州宇泛智能科技有限公司': '杭州宇泛智能科技股份有限公司',
 '深圳赛飞百步印社科技有限公司': '深圳百步印社科技有限公司',
 '上海商汤临港智能科技有限公司': '上海临港绝影智能科技有限公司',
 '慧影医疗科技（北京）有限公司': '慧影医疗科技（北京）股份有限公司',
 '杭州坤泽实业股份有限公司': '杭州坤泽控股有限公司',
 '广州市易鸿智能装备有限公司': '广州市易鸿智能装备股份有限公司',
 '江苏神州信源系统工程有限公司': '北信源系统集成有限公司',
 '合肥中导机器人科技有限公司': '浙江众导机器人科技有限公司',
 '上海电气风电集团有限公司': '上海电气风电集团股份有限公司',
 '深圳蓝韵医学影像有限公司': '深圳蓝影医学科技股份有限公司',
 '紫光华山信息技术有限公司': '新华三信息技术有限公司',
 '银河水滴科技（北京）有限公司': '银河水滴科技（江苏）有限公司',
 '江苏中兴微通信息科技有限公司': '南京仄普托信息科技有限公司',
 '上海优加利健康管理有限公司': '上海乐普云智科技股份有限公司',
 '深圳市鹰硕教育服务有限公司': '深圳市鹰硕智能科技有限公司',
 '全成信电子（深圳）股份有限公司': '深圳全成信电子有限公司',
 '合肥埃科光电科技有限公司': '合肥埃科光电科技股份有限公司',
 '惠州旭鑫智能技术有限公司': '安徽瑞视微智能科技有限公司',
 '无锡华云数据技术服务有限公司': '华云数据控股集团有限公司',
 '北京格元智博科技有限公司': '北京觅机科技有限公司',
 '国网湖南省电力公司': '国网湖南省电力有限公司',
 '深圳市创梦天地科技股份有限公司': '深圳市创梦天地科技有限公司',
 '河北中科恒运软件科技股份有限公司': '中科恒运股份有限公司',
 '南京积图网络科技有限公司': '南京交控积图网络科技有限公司',
 '圣凯诺服饰有限公司': '江阴恒创服饰有限公司',
 '北京睿信丰科技有限公司': '睿信丰空天科技（北京）股份有限公司',
 '国网黑龙江省电力有限公司检修公司': '国网黑龙江省电力有限公司超高压公司',
 '鞍钢集团矿业公司': '鞍钢集团矿业有限公司',
 '华为终端（东莞）有限公司': '华为终端有限公司',
 '重庆零壹空间科技集团有限公司': '重庆零壹空间科技股份有限公司',
 '无锡中星微电子有限公司': '无锡中感微电子股份有限公司',
 '浙江合众新能源汽车有限公司': '合众新能源汽车有限公司',
 '武汉钢铁（集团）公司': '武钢集团有限公司',
 '合一信息技术（北京）有限公司': '优酷信息技术（北京）有限公司',
 '北京牡丹电子集团有限责任公司数字电视技术中心': '北京牡丹电子集团有限责任公司数字科技中心',
 '成都安健发科技有限公司': '成都佳发安泰信息工程有限公司',
 '上海芯仑光电科技有限公司': '豪威芯仑传感器（上海）有限公司',
 '深圳市迈唐科技发展有限公司': '深圳市迈唐科技有限公司',
 '深圳市泽峰光电科技有限公司': '苏州市泽峰光电科技有限公司',
 '福建帝视信息科技有限公司': '福建帝视科技集团有限公司',
 '沈阳东软医疗系统有限公司': '东软医疗系统股份有限公司',
 '上海景吾智能科技有限公司': '杭州景吾智能科技有限公司',
 '龙芯中科技术有限公司': '龙芯中科技术股份有限公司',
 '福州瑞芯微电子股份有限公司': '瑞芯微电子股份有限公司',
 '北京展讯高科通信技术有限公司': '北京紫光展锐通信技术有限公司',
 '北京晶品特装科技有限责任公司': '北京晶品特装科技股份有限公司',
 '国家电网公司信息通信分公司': '国家电网有限公司信息通信分公司',
 '云集网络（大连）股份有限公司': '云集网络（大连）有限公司',
 '深圳佑驾创新科技有限公司': '深圳佑驾创新科技股份有限公司',
 '苏州科阳光电科技有限公司': '苏州科阳半导体有限公司',
 '华电国际宁夏新能源发电有限公司': '华电（宁夏）能源有限公司',
 '浪潮天元通信信息系统有限公司': '浪潮通信信息系统有限公司',
 '南京视察者图像识别科技有限公司': '南京视察者智能科技有限公司',
 '北京字节跳动科技有限公司': '北京抖音信息服务有限公司',
 '浙江陀曼精密机械有限公司': '浙江陀曼智能科技股份有限公司',
 '上海金仕达软件科技有限公司': '上海金仕达软件科技股份有限公司',
 '魅族科技（中国）有限公司': '珠海市魅族科技有限公司',
 '中科豪联（杭州）技术有限公司': '中科豪联（温州）技术有限公司',
 '山东众阳健康科技集团有限公司': '众阳健康科技集团有限公司',
 '北京经纬恒润科技有限公司': '北京经纬恒润科技股份有限公司',
 '欧菲影像技术（广州）有限公司': '广州得尔塔影像技术有限公司',
 '北京天诚盛业科技有限公司': '北京眼神智能科技有限公司',
 '鸿富锦精密电子（天津）有限公司': '富联精密电子（天津）有限公司',
 '北京天睿空间科技有限公司': '北京天睿空间科技股份有限公司',
 '上海创远仪器技术股份有限公司': '创远信科（上海）技术股份有限公司',
 '中国葛洲坝集团基础工程有限公司': '中国葛洲坝集团市政工程有限公司',
 '中惠创智无线供电技术有限公司': '烟台凌晟电力科技有限公司',
 '中国铁路总公司': '中国国家铁路集团有限公司',
 '常州格力博有限公司': '格力博（江苏）股份有限公司',
 '山东鲁能智能技术有限公司': '国网智能科技股份有限公司',
 '南京安元科技有限公司': '安元科技股份有限公司',
 '湖南金杯新能源发展有限公司': '湖南容创科技有限公司',
 '武汉达梦数据库有限公司': '武汉达梦数据库股份有限公司',
 '塞伯睿机器人技术（长沙）有限公司': '塞伯睿机器人技术（南京）有限公司',
 '中国建筑设计咨询有限公司': '中国城市发展规划设计咨询有限公司',
 '安一恒通（北京）科技有限公司': '度小满安一科技（北京）有限公司',
 '南宁富桂精密工业有限公司': '南宁富联富桂精密工业有限公司',
 '深圳市佳信捷技术股份有限公司': '江西佳信捷电子股份有限公司',
 '珠海易胜电子技术有限公司': '珠海易胜智能科技有限公司',
 '重庆电信系统集成有限公司': '中电智安科技有限公司',
 '深圳英集芯科技有限公司': '深圳英集芯科技股份有限公司',
 '北京宝沃汽车有限公司': '北京宝沃汽车股份有限公司',
 '泰亿格电子（上海）有限公司': '上海泰亿格康复医疗科技股份有限公司',
 '深圳市双新环保科技有限公司': '深圳市启明城市环境产业服务有限公司',
 '深圳市金正方科技股份有限公司': '深圳金正方科技股份有限公司',
 '中建科技有限公司深圳分公司': '中建科技集团有限公司深圳分公司',
 '深圳指芯智能科技有限公司': '江西指芯智能科技有限公司',
 '北京贝塔科技股份有限公司': '北京贝塔科技有限公司',
 '深圳市裕展精密科技有限公司': '富联裕展科技（深圳）有限公司',
 '征图新视（江苏）科技有限公司': '征图新视（江苏）科技股份有限公司',
 '北京格灵深瞳信息技术有限公司': '北京格灵深瞳信息技术股份有限公司',
 '广州宝荣科技应用有限公司': '智慧中医科技（广东）有限公司',
 '中船重工鹏力（南京）大气海洋信息系统有限公司': '中船鹏力（南京）大气海洋信息系统有限公司',
 '北京五八到家信息技术有限公司': '北京五八到家信息技术集团有限公司',
 '中国建材检验认证集团股份有限公司': '中国国检测试控股集团股份有限公司',
 '超威电源有限公司': '超威电源集团有限公司',
 '北京柏惠维康科技有限公司': '北京柏惠维康科技股份有限公司',
 '深圳市博铭维智能科技有限公司': '深圳市博铭维技术股份有限公司',
 '北京臻迪科技股份有限公司': '臻迪科技股份有限公司',
 '广州汇通国信信息科技有限公司': '广州汇通国信科技有限公司',
 '北京中科睿芯科技有限公司': '北京中科睿芯科技集团有限公司',
 '伽蓝（集团）股份有限公司': '上海自然堂集团有限公司',
 '宿州市诚泰科技有限公司': '安徽省诚泰科技有限公司',
 '北京中宸泓昌科技有限公司': '北京中宸微电子有限公司',
 '湘潭人人安居信息技术有限公司': '湖南人人安居科技有限公司',
 '杭州普维光电技术有限公司': '杭州普维云技术有限公司',
 '深圳市邦彦信息技术有限公司': '邦彦技术股份有限公司',
 '广西美澳妇产医院有限公司': '美澳医院（广西）有限公司',
 '南京阿福机器人有限公司': '苏州阿福机器人有限公司',
 '九康智能科技（广州）有限公司': '力鲜农智能科技（广州）有限公司',
 '普天信息技术研究院有限公司': '普天信息技术有限公司',
 '广州慧睿思通信息科技有限公司': '广州慧睿思通科技股份有限公司',
 '深圳市前海安测信息技术有限公司': '深圳市安测健康信息技术有限公司',
 '上海荣盛生物药业有限公司': '上海荣盛生物药业股份有限公司',
 '深圳市中兴移动通信有限公司': '努比亚技术有限公司',
 '广东电网公司': '广东电网有限责任公司',
 '杭州得康蓄电池修复仪有限公司': '杭州得康智能设备有限公司',
 '杭州安恒信息技术有限公司': '杭州安恒信息技术股份有限公司',
 '曙光云计算集团有限公司': '曙光云计算集团股份有限公司',
 '润联软件系统（深圳）有限公司': '华润数字科技有限公司',
 '杭州绿宇中科检测技术有限公司': '浙江绿宇中科检测技术有限公司',
 '深圳掌智付信息科技有限公司': '深圳市宏杰信科技有限公司',
 '福建省宜品生物科技有限公司': '福建省宜品嘉成科技有限公司',
 '重庆扬讯软件技术股份有限公司': '重庆扬讯数字科技股份有限公司',
 '深圳前海勇艺达机器人有限公司': '深圳勇艺达机器人有限公司',
 '乐鑫信息科技（上海）有限公司': '乐鑫信息科技（上海）股份有限公司',
 '成都极米科技股份有限公司': '极米科技股份有限公司',
 '北京西山居互动娱乐科技有限公司': '北京金山世游互动娱乐科技有限公司',
 '国网安徽省电力公司淮南供电公司': '国网安徽省电力有限公司淮南供电公司',
 '北京奇安信科技有限公司': '奇安信科技集团股份有限公司',
 '渭南高新区木王科技有限公司': '渭南木王智能科技股份有限公司',
 '杭州凯尔达机器人科技股份有限公司': '杭州凯尔达焊接机器人股份有限公司',
 '中睿通信规划设计有限公司': '中通服中睿科技有限公司',
 '上海科梁信息工程股份有限公司': '上海科梁信息科技股份有限公司',
 '深圳市芯海科技有限公司': '芯海科技（深圳）股份有限公司',
 '深圳市瑞驰文体发展有限公司': '深圳市瑞驰文体科技发展有限公司',
 '珠海赛纳打印科技股份有限公司': '珠海赛纳科技有限公司',
 '浙江万朋教育科技股份有限公司': '浙江万朋数智科技股份有限公司',
 '成都市克莱微波科技有限公司': '四川省华盾防务科技股份有限公司',
 '长春轨道客车股份有限公司': '中车长春轨道客车股份有限公司',
 '江苏软仪科技股份有限公司': '江苏软仪科技集团股份有限公司',
 '深圳市亿联无限科技有限公司': '深圳市亿联无限科技股份有限公司',
 '河南省保时安电子科技有限公司': '河南省保时安科技股份有限公司',
 '深圳市铁汉生态环境股份有限公司': '中节能铁汉生态环境股份有限公司',
 '长扬科技（北京）有限公司': '长扬科技（北京）股份有限公司',
 '黄河勘测规划设计有限公司': '黄河勘测规划设计研究院有限公司',
 '华文包装股份有限公司': '华文包装有限责任公司',
 '江苏天诚智能集团有限公司': '江苏天诚智能集团股份有限公司',
 '苏州上舜精密工业科技有限公司': '苏州上舜科技股份有限公司',
 '成都能通科技有限公司': '成都能通科技股份有限公司',
 '东莞市速美达自动化有限公司': '广东速美达自动化股份有限公司',
 '国网江西省电力公司信息通信分公司': '国网江西省电力有限公司信息通信分公司',
 '内蒙古小草数字生态产业有限公司': '内蒙古小草数字生态产业股份有限公司',
 '四川秘无痕信息安全技术有限责任公司': '四川秘无痕科技有限责任公司',
 '躺平设计家（北京）科技有限公司': '每平每屋设计家（北京）科技有限公司',
 '惠州高盛达科技有限公司': '惠州高盛达科技股份有限公司',
 '中国华戎控股有限公司': '中国华戎科技集团有限公司',
 '中国葛洲坝集团第六工程有限公司': '中国葛洲坝集团建设工程有限公司',
 '恩施京植咿呀雅口腔医院有限公司': '咿呀英博（湖北）控股集团有限公司',
 '北京四季豆信息技术有限公司': '芯象半导体科技（北京）有限公司',
 '北京永新医疗设备有限公司': '成都永新医疗设备有限公司',
 '国网安徽省电力公司合肥供电公司': '国网安徽省电力有限公司合肥供电公司',
 '武汉卓目科技有限公司': '武汉卓目科技股份有限公司',
 '北京兆易创新科技股份有限公司': '兆易创新科技集团股份有限公司',
 '广东和顺物业管理有限公司': '广东省广晟城市服务有限公司',
 '宽凳（北京）科技有限公司': '宽凳（湖州）科技有限公司',
 '武汉图科智能科技有限公司': '杭州图科智能信息科技有限公司',
 '广东威创视讯科技股份有限公司': '威创集团股份有限公司',
 '澜起科技（上海）有限公司': '澜起科技股份有限公司',
 '无锡华润矽科微电子有限公司': '华润微集成电路（无锡）有限公司',
 '成都华微电子科技有限公司': '成都华微电子科技股份有限公司',
 '天津飞腾信息技术有限公司': '飞腾信息技术有限公司',
 '四川东方电气自动控制工程有限公司': '东方电气自动控制工程有限公司',
 '至誉科技（武汉）有限公司': '至誉科技股份有限公司',
 '深圳市微克科技有限公司': '深圳市微克科技股份有限公司',
 '易通远见（北京）科技有限公司': '北京航天联智科技有限公司',
 '杭州阅光医疗科技有限公司': '杭州烁安电子商务有限公司',
 '深圳大普微电子科技有限公司': '深圳大普微电子股份有限公司',
 '磅客策（上海）机器人有限公司': '磅客策（上海）智能医疗科技有限公司',
 '深圳市彬讯科技有限公司': '土巴兔集团股份有限公司',
 '广东万引科技发展有限公司': '广东万引科技股份有限公司',
 '北京深思数盾科技股份有限公司': '北京深盾科技股份有限公司',
 '国网安徽省电力公司宿州供电公司': '国网安徽省电力有限公司宿州供电公司',
 '重庆长安铃木汽车有限公司': '重庆铃耀汽车有限公司',
 '深圳优地科技有限公司': '优地机器人（无锡）有限公司',
 '国久大数据有限公司': '国久大数据股份有限公司',
 '郑州禅图智能科技有限公司': '河南未来空间规划建设有限公司',
 '北京德风新征程科技有限公司': '北京德风新征程科技股份有限公司',
 '天能电池集团有限公司': '天能电池集团股份有限公司',
 '昆山龙腾光电有限公司': '昆山龙腾光电股份有限公司',
 '四川知周光声医疗科技有限公司': '四川中川新迈光声医疗科技有限公司',
 '南京南瑞集团公司': '南瑞集团有限公司',
 '苏宁金融科技（南京）有限公司': '南京星云数字技术有限公司',
 '大唐高鸿信息通信研究院（义乌）有限公司': '大唐高鸿信息通信（义乌）有限公司',
 '福州汇思博信息技术有限公司': '福建汇思博数字科技有限公司',
 '北京云知声信息技术有限公司': '云知声智能科技股份有限公司',
 '中国海洋石油总公司': '中国海洋石油集团有限公司',
 '杭州雄迈集成电路技术股份有限公司': '浙江芯劢微电子股份有限公司',
 '北京神州绿盟信息安全科技股份有限公司': '绿盟科技集团股份有限公司',
 '南京云图机器人科技有限公司': '江苏云图机器人有限公司',
 '山东金利康面粉有限公司': '山东金利康食品科技股份有限公司',
 '西安诺瓦电子科技有限公司': '西安诺瓦星云科技股份有限公司',
 '苏州英菲泰尔电子科技有限公司': '苏州开阳微电子有限公司',
 '东莞市度润光电科技有限公司': '广东度润光电科技有限公司',
 '广州欧纬德教学设备技术有限公司': '欧纬德智能科技（广州）有限公司',
 '北京安控科技股份有限公司': '四川安控科技股份有限公司',
 '盎锐（上海）信息科技有限公司': '盎锐（杭州）信息科技有限公司',
 '西安中科微光影像技术有限公司': '中科微光医疗研究中心（西安）有限公司',
 '泰凌微电子（上海）有限公司': '泰凌微电子（上海）股份有限公司',
 '武汉日电光通信工业有限公司': '武汉众邦领创技术有限公司',
 '上海数据交易中心有限公司': '上海数据发展科技有限责任公司',
 '浙江国自机器人技术有限公司': '浙江国自机器人技术股份有限公司',
 '江西省高速公路投资集团有限责任公司': '江西省交通投资集团有限责任公司',
 '上海摩镶数据科技有限公司': '上海相沫数据科技有限公司',
 '北京拓尔思信息技术股份有限公司': '拓尔思信息技术股份有限公司',
 '山东华硕汽车配件科技有限公司': '山东华硕动力科技有限公司',
 '深圳市中智科创机器人有限公司': '中智科创机器人有限公司',
 '广东易事特电源股份有限公司': '易事特集团股份有限公司',
 '青岛创新奇智科技集团有限公司': '青岛创新奇智科技集团股份有限公司',
 '四川华雁信息产业股份有限公司': '华雁智能科技（集团）股份有限公司',
 '宁波纵横信息技术有限公司': '浙江纵横软件有限公司',
 '中国船舶重工集团南京鹏力科技集团有限公司': '中船鹏力（南京）科技集团有限公司',
 '苏州鸿凌达电子科技有限公司': '苏州鸿凌达电子科技股份有限公司',
 '北京富吉瑞光电科技有限公司': '北京富吉瑞光电科技股份有限公司',
 '北京农信互联科技有限公司': '北京农信互联科技集团有限公司',
 '上海新炬网络信息技术有限公司': '上海新炬网络信息技术股份有限公司',
 '深圳市鼎阳科技有限公司': '深圳市鼎阳科技股份有限公司',
 '山东青橙视联信息科技有限公司': '山东青橙数字科技有限公司',
 '广州致远电子有限公司': '广州致远电子股份有限公司',
 '宏远智控科技（北京）有限公司': '北京宏远智控技术有限公司',
 '光脚信息科技（南京）有限公司': '南京光脚科技有限公司',
 '星辰天合（北京）数据科技有限公司': '北京星辰天合科技股份有限公司',
 '成都博智维讯信息技术有限公司': '成都博智维讯信息技术股份有限公司',
 '山东鲁能软件技术有限公司': '山东鲁软数字科技有限公司',
 '浙江华鹰风电设备有限公司': '浙江佑立建设工程有限公司',
 '上海证券交易所': '上海证券交易所（中国证券博物馆）',
 '骐俊通联（厦门）科技有限公司': '三际通联（厦门）科技有限公司',
 '南京熙健信息技术有限公司': '南京熙健电子科技有限公司',
 '贵州电网公司信息通信分公司': '贵州电网有限责任公司信息中心',
 '蜂巢能源科技有限公司': '蜂巢能源科技股份有限公司',
 '天津市电力公司': '国网天津市电力公司',
 '北京华开领航科技有限责任公司': '北京运达华开科技有限公司',
 '广东电网公司潮州供电局': '广东电网有限责任公司潮州供电局',
 '深圳市英博超算科技有限公司': '英博超算（南京）科技有限公司',
 '北京合康亿盛变频科技股份有限公司': '北京合康新能科技股份有限公司',
 '广东高新兴通信股份有限公司': '高新兴科技集团股份有限公司',
 '北京华电天仁电力控制技术有限公司': '国能信控互联技术有限公司',
 '大陆汽车投资（上海）有限公司': '大陆投资（中国）有限公司',
 '国网安徽省电力公司': '国网安徽省电力有限公司',
 '上海贝尔股份有限公司': '上海诺基亚贝尔股份有限公司',
 '深圳市哈工大交通电子技术有限公司': '深圳市哈工交通电子有限公司',
 '华勤技术有限公司': '华勤技术股份有限公司',
 '佛山市新鹏机器人技术有限公司': '广东汇博机器人技术有限公司',
 '成都金盘电子科大多媒体技术有限公司': '成都成电金盘健康数据技术有限公司',
 '深圳市核达中远通电源技术有限公司': '深圳市核达中远通电源技术股份有限公司',
 '湖南创合制造有限公司': '湖南铱索机电制造有限公司',
 '北京北方微电子基地设备工艺研究中心有限责任公司': '北京北方华创微电子装备有限公司',
 '安科智慧城市技术（中国）有限公司': '安科机器人有限公司',
 '中电科仪器仪表有限公司': '中电科思仪科技股份有限公司',
 '北京千丁互联科技有限公司': '北京千丁智能技术有限公司',
 '威格气体纯化科技（苏州）股份有限公司': '威格科技（苏州）股份有限公司',
 '中山市世宇动漫科技有限公司': '广东世宇科技股份有限公司',
 '中绿农农业发展有限公司': '中绿农农业集团有限公司',
 '广东东博自动化设备有限公司': '广东东博智能装备股份有限公司',
 '苏州阿格斯医疗技术有限公司': '苏州微创阿格斯医疗科技有限公司',
 '北京天碁科技有限公司': '意法·爱立信半导体（北京）有限公司',
 '上海广联电子有限公司': '津亚高科智能设备（上海）有限公司',
 '中煤科工集团重庆研究院有限公司': '煤炭科学研究总院重庆研究院',
 '北京启明星辰信息技术股份有限公司': '启明星辰信息技术集团股份有限公司',
 '信帧电子技术（北京）有限公司': '信帧机器人技术（北京）有限公司',
 '淄博前沿医疗器械有限公司': '山东前沿医疗器械股份有限公司',
 '北京云天时空科技有限公司': '云信网联（北京）科技有限公司',
 '中国大唐集团科学技术研究院有限公司': '中国大唐集团科学技术研究总院有限公司',
 '锤子科技（北京）有限公司': '锤子科技（北京）股份有限公司',
 '深圳市海德森科技有限公司': '深圳市海德森科技股份有限公司',
 '深圳市晶福源电子技术有限公司': '深圳晶福源科技股份有限公司',
 '青岛英网资讯股份有限公司': '山东英网资讯股份有限公司',

In [66]:
citing_assignee_list,cited_assignee_list = [],[]
for index in read_data.index:
    row_data = read_data.iloc[index]
    row_citing_assignee,row_cited_assignee = row_data['citing_assignee'], row_data['cited_assignee']
    citing_assignee_pure = []
    for key in row_citing_assignee.split(";"):
        if key.strip() in key_value:
            citing_assignee_pure.append(key_value[key.strip()])
        else:
            citing_assignee_pure.append(key.strip())

    citing_assignee_string = ';'.join(citing_assignee_pure)
    citing_assignee_list.append(citing_assignee_string)

    cited_assignee_pure = []
    for key2 in row_cited_assignee.split(";"):
        if key2.strip() in key_value:
            cited_assignee_pure.append(key_value[key2.strip()])
        else:
            cited_assignee_pure.append(key2.strip())
    cited_assignee_string = ';'.join(cited_assignee_pure)
    cited_assignee_list.append(cited_assignee_string)
    if index%100 == 0:
        print(index)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800
29900
30000
30100
30200
30300
30400
30500
30600
30700
30800
30900
31000
31100
31200
31300
31400
31500
31600
31700
31800
31900
32000
32100
32200
32300
32400
32500
32600
32700
32800
32900
33000
33100
33200
33300
33400
33500
33600
33700
33800
33900
34000
34100
34200
34300
34400
34500
34600
34700
34800
34900
35000
35100
35200
35300
35400
35500
35600
35700
35800
35900
36000
36100
36200
36300
36400
36500
36600
36700
36800
36900
37000
37100
37200
37300
37400
37500
37600
37700
37800
37900
38000
38100
38200
38300
38400
38500
38600
38700
38800
38900
39000
39100
39200
39300
39400
39500
39600
39700
39800
39900
40000
40100
40200
40300
40400
40500
40600
40700
40800
40900
41000
41100
41200
41300
41400
41500
41600
41700
41800
41900
42000
42100
42200
42300
42400
42500
42600
42700
42800
42900
43000
43100
43200
43300
43400
43500
43600
43700
43800
43900
44000
44100
44200
44300
44400
44500
44600
44700
44800
44900
45000
45100
45200
45300
45400
45500
45600
45700
45800
45900
46000
46100
46200
46300
46400
46500
46600
46700
46800
46900
47000
47100
47200
47300
47400
47500
47600
47700
47800
47900
48000
48100
48200
48300
48400
48500
48600
48700
48800
48900
49000
49100
49200
49300
49400
49500
49600
49700
49800
49900
50000
50100
50200
50300
50400
50500
50600
50700
50800
50900
51000
51100
51200
51300
51400
51500
51600
51700
51800
51900
52000
52100
52200
52300
52400
52500
52600
52700
52800
52900
53000
53100
53200
53300
53400
53500
53600
53700
53800
53900
54000
54100
54200
54300
54400
54500
54600
54700
54800
54900
55000
55100
55200
55300
55400
55500
55600
55700
55800
55900
56000
56100
56200
56300
56400
56500
56600
56700
56800
56900
57000
57100
57200
57300
57400
57500
57600
57700
57800
57900
58000
58100
58200
58300
58400
58500
58600
58700
58800
58900
59000
59100
59200
59300
59400
59500
59600
59700
59800
59900
60000
60100
60200
60300
60400
60500
60600
60700
60800
60900
61000
61100
61200
61300
61400
61500
61600
61700
61800
61900
62000
62100
62200
62300
62400
62500
62600
62700
62800
62900
63000
63100
63200
63300
63400
63500
63600
63700
63800
63900
64000
64100
64200
64300
64400
64500
64600
64700
64800
64900
65000
65100
65200
65300
65400
65500
65600
65700
65800
65900
66000
66100
66200
66300
66400
66500
66600
66700
66800
66900
67000
67100
67200
67300
67400
67500
67600
67700
67800
67900
68000
68100
68200
68300
68400
68500
68600
68700
68800
68900
69000
69100
69200
69300
69400
69500
69600
69700
69800
69900
70000
70100
70200
70300
70400
70500
70600
70700
70800
70900
71000
71100
71200
71300
71400
71500
71600
71700
71800
71900
72000
72100
72200
72300
72400
72500
72600
72700
72800
72900
73000
73100
73200
73300
73400
73500
73600
73700
73800
73900
74000
74100
74200
74300
74400
74500
74600
74700
74800
74900
75000
75100
75200
75300
75400
75500
75600
75700
75800
75900
76000
76100
76200
76300
76400
76500
76600
76700
76800
76900
77000
77100
77200
77300
77400
77500
77600
77700
77800
77900
78000
78100
78200
78300
78400
78500
78600
78700
78800
78900
79000
79100
79200
79300
79400
79500
79600
79700
79800
79900
80000
80100
80200
80300
80400
80500
80600
80700
80800
80900
81000
81100
81200
81300
81400
81500
81600
81700
81800
81900
82000
82100
82200
82300
82400
82500
82600
82700
82800
82900
83000
83100
83200
83300
83400
83500
83600
83700
83800
83900
84000
84100
84200
84300
84400
84500
84600
84700
84800
84900
85000
85100
85200
85300
85400
85500
85600
85700
85800
85900
86000
86100
86200
86300
86400
86500
86600
86700
86800
86900
87000
87100
87200
87300
87400
87500
87600
87700
87800
87900
88000
88100
88200
88300
88400
88500
88600
88700
88800
88900
89000
89100
89200
89300
89400
89500
89600
89700
89800
89900
90000
90100
90200
90300
90400
90500
90600
90700
90800
90900
91000
91100
91200
91300
91400
91500
91600
91700
91800
91900
92000
92100
92200
92300
92400
92500
92600
92700
92800
92900
93000
93100
93200
93300
93400
93500
93600
93700
93800
93900
94000
94100
94200
94300
94400
94500
94600
94700
94800
94900
95000
95100
95200
95300
95400
95500
95600
95700
95800
95900
96000
96100
96200
96300
96400
96500
96600
96700
96800
96900
97000
97100
97200
97300
97400
97500
97600
97700
97800
97900
98000
98100
98200
98300
98400
98500
98600
98700
98800
98900
99000
99100
99200
99300
99400
99500
99600
99700
99800
99900
100000
100100
100200
100300
100400
100500
100600
100700
100800
100900
101000
101100
101200
101300
101400
101500
101600
101700
101800
101900
102000
102100
102200
102300
102400
102500
102600
102700
102800
102900
103000
103100
103200
103300
103400
103500
103600
103700
103800
103900
104000
104100
104200
104300
104400
104500
104600
104700
104800
104900
105000
105100
105200
105300
105400
105500
105600
105700
105800
105900
106000
106100
106200
106300
106400
106500
106600
106700
106800
106900
107000
107100
107200
107300
107400
107500
107600
107700
107800
107900
108000
108100
108200
108300
108400
108500
108600
108700
108800
108900
109000
109100
109200
109300
109400
109500
109600
109700
109800
109900
110000
110100
110200
110300
110400
110500
110600
110700
110800
110900
111000
111100
111200
111300
111400
111500
111600
111700
111800
111900
112000
112100
112200
112300
112400
112500
112600
112700
112800
112900
113000
113100
113200
113300
113400
113500
113600
113700
113800
113900
114000
114100
114200
114300
114400
114500
114600
114700
114800
114900
115000
115100
115200
115300
115400
115500
115600
115700
115800
115900
116000
116100
116200
116300
116400
116500
116600
116700
116800
116900
117000
117100
117200
117300
117400
117500
117600
117700
117800
117900
118000
118100
118200
118300
118400
118500
118600
118700
118800
118900
119000
119100
119200
119300
119400
119500
119600
119700
119800
119900
120000
120100
120200
120300
120400
120500
120600
120700
120800
120900
121000
121100
121200
121300
121400
121500
121600
121700
121800
121900
122000
122100
122200
122300
122400
122500
122600
122700
122800
122900
123000
123100
123200
123300
123400
123500
123600
123700
123800
123900
124000
124100
124200
124300
124400
124500
124600
124700
124800
124900
125000
125100
125200
125300
125400
125500
125600
125700
125800
125900
126000
126100
126200
126300
126400
126500
126600
126700
126800
126900
127000
127100
127200
127300
127400
127500
127600
127700
127800
127900
128000
128100
128200
128300
128400
128500
128600
128700
128800
128900
129000
129100
129200
129300
129400
129500
129600
129700
129800
129900
130000
130100
130200
130300
130400
130500
130600
130700
130800
130900
131000
131100
131200
131300
131400
131500
131600
131700
131800
131900
132000
132100
132200
132300
132400
132500
132600
132700
132800
132900
133000
133100
133200
133300
133400
133500
133600
133700
133800
133900
134000
134100
134200
134300
134400
134500
134600
134700
134800
134900
135000
135100
135200
135300
135400
135500
135600
135700
135800
135900
136000
136100
136200
136300
136400
136500
136600
136700
136800
136900
137000
137100
137200
137300
137400
137500
137600
137700
137800
137900
138000
138100
138200
138300
138400
138500
138600
138700
138800
138900
139000
139100
139200
139300
139400
139500
139600
139700
139800
139900
140000
140100
140200
140300
140400
140500
140600
140700
140800
140900
141000
141100
141200
141300
141400
141500
141600
141700
141800
141900
142000
142100
142200
142300
142400
142500
142600
142700
142800
142900
143000
143100
143200
143300
143400
143500
143600
143700
143800
143900
144000
144100
144200
144300
144400
144500
144600
144700
144800
144900
145000
145100
145200
145300
145400
145500
145600
145700
145800
145900
146000
146100
146200
146300
146400
146500
146600
146700
146800
146900
147000
147100
147200
147300
147400
147500
147600
147700
147800
147900
148000
148100
148200
148300
148400
148500
148600
148700
148800
148900
149000
149100
149200
149300
149400
149500
149600
149700
149800
149900
150000
150100
150200
150300
150400
150500
150600
150700
150800
150900
151000
151100
151200
151300
151400
151500
151600
151700
151800
151900
152000
152100
152200
152300
152400
152500
152600
152700
152800
152900
153000
153100
153200
153300
153400
153500
153600
153700
153800

In [67]:
read_data['citing_assignee_pure'] = citing_assignee_list
read_data['cited_assignee_pure'] = cited_assignee_list

In [69]:
read_data.to_excel("./results/result_temp_data2.xlsx",index=None)

# 处理边数据

In [84]:
read_data

,citing_no,citing_date,citing_assignee,cited_no,cited_date,cited_assignee,citing_cited,citing_assignee_pure,cited_assignee_pure
0,CN105844614B,2016-03-15,广东工业大学,CN105260710B,2015-09-28,北京石油化工学院,CN105844614B_CN105260710B,广东工业大学,北京石油化工学院
1,CN112214368B,2020-10-23,英业达科技有限公司;英业达股份有限公司,CN105224430B,2015-10-29,艾德克斯电子（南京）有限公司,CN112214368B_CN105224430B,英业达科技有限公司;英业达股份有限公司,艾德克斯电子（南京）有限公司
2,CN112910720B,2021-05-06,成都云智天下科技股份有限公司,CN105245362B,2015-09-14,河南工业大学; 西安电子科技大学,CN112910720B_CN105245362B,成都云智天下科技股份有限公司,河南工业大学;西安电子科技大学
3,CN104608125B,2013-11-01,精工爱普生株式会社,CN105234938B,2011-07-11,精工爱普生株式会社,CN104608125B_CN105234938B,精工爱普生株式会社,精工爱普生株式会社
4,CN106239505B,2016-08-01,广东电网有限责任公司电力科学研究院,CN105234938B,2011-07-11,精工爱普生株式会社,CN106239505B_CN105234938B,广东电网有限责任公司电力科学研究院,精工爱普生株式会社
...,...,...,...,...,...,...,...,...,...
153818,CN113205509B,2021-05-24,山东省人工智能研究院;齐鲁工业大学,CN111709925B,2020-06-11,深圳科亚医疗科技有限公司,CN113205509B_CN111709925B,山东省人工智能研究院;齐鲁工业大学,深圳科亚医疗科技有限公司
153819,CN115272165B,2022-05-10,推想医疗科技股份有限公司,CN111709925B,2020-06-11,深圳科亚医疗科技有限公司,CN115272165B_CN111709925B,推想医疗科技股份有限公司,深圳科亚医疗科技有限公司
153820,CN115222665B,2022-06-13,北京医准智能科技有限公司,CN111709925B,2020-06-11,深圳科亚医疗科技有限公司,CN115222665B_CN111709925B,浙江医准智能科技有限公司,深圳科亚医疗科技有限公司
153821,CN110596328B,2019-06-25,北京机械设备研究所,CN107449874B,2017-09-13,中国科学院地理科学与资源研究所,CN110596328B_CN107449874B,北京机械设备研究所,中国科学院地理科学与资源研究所
153822,CN110355755B,2018-12-15,深圳铭杰医疗科技有限公司,CN107127755B,2017-05-12,华南理工大学,CN110355755B_CN107127755B,深圳铭杰医疗科技有限公司,华南理工大学

In [85]:
citing_data = read_data[['citing_no','citing_assignee_pure']]
citing_data

           citing_no citing_assignee_pure
0       CN105844614B               广东工业大学
1       CN112214368B  英业达科技有限公司;英业达股份有限公司
2       CN112910720B       成都云智天下科技股份有限公司
3       CN104608125B            精工爱普生株式会社
4       CN106239505B    广东电网有限责任公司电力科学研究院
...              ...                  ...
153818  CN113205509B    山东省人工智能研究院;齐鲁工业大学
153819  CN115272165B         推想医疗科技股份有限公司
153820  CN115222665B         浙江医准智能科技有限公司
153821  CN110596328B            北京机械设备研究所
153822  CN110355755B         深圳铭杰医疗科技有限公司

[153823 rows x 2 columns]

In [81]:
type_data = pd.read_excel("./results/result_temp_data.xlsx", sheet_name=8)

In [82]:
replace_dict = {'I': 1, 'E': 2, 'U': 3, 'R': 3}
type_data['Assignee_score'] = type_data['Assignee_type'].replace(replace_dict)
type_data

          citing_assignee Assignee_type  Assignee_score
0                     金阳娃             I               1
1                      王伟             I               1
2                     王华锋             I               1
3                     居鹤华             I               1
4                      崔洋             I               1
...                   ...           ...             ...
17565        广东美的楼宇科技有限公司             E               2
17566        江苏济中能源技术有限公司             E               2
17567          上海宝冶集团有限公司             E               2
17568  大田基业投资管理咨询（北京）有限公司             E               2
17569            中盟科技有限公司             E               2

[17570 rows x 3 columns]

In [86]:
citing_temp = []
for index in citing_data.index:
    citing_no,assignees = citing_data.iloc[index]['citing_no'],citing_data.iloc[index]['citing_assignee_pure']
    split_assignees = assignees.split(";")
    combine_flag = True if len(split_assignees)>1 else False
    for i in range(len(split_assignees)):
        citing_temp.append({"citing":citing_no,"order":i+1,"citing_assignee":split_assignees[i],"is_combine":combine_flag})

In [87]:
citing_df = pd.DataFrame(citing_temp)
citing_df

              citing  order citing_assignee  is_combine
0       CN105844614B      1          广东工业大学       False
1       CN112214368B      1       英业达科技有限公司        True
2       CN112214368B      2       英业达股份有限公司        True
3       CN112910720B      1  成都云智天下科技股份有限公司       False
4       CN104608125B      1       精工爱普生株式会社       False
...              ...    ...             ...         ...
168740  CN113205509B      2          齐鲁工业大学        True
168741  CN115272165B      1    推想医疗科技股份有限公司       False
168742  CN115222665B      1    浙江医准智能科技有限公司       False
168743  CN110596328B      1       北京机械设备研究所       False
168744  CN110355755B      1    深圳铭杰医疗科技有限公司       False

[168745 rows x 4 columns]

In [88]:
citing_merge = pd.merge(citing_df,type_data,on='citing_assignee')

,citing,order,citing_assignee,is_combine,Assignee_type,Assignee_score
0,CN105844614B,1,广东工业大学,False,U,3
1,CN109492546B,1,广东工业大学,False,U,3
2,CN107443373B,1,广东工业大学,False,U,3
3,CN106041932B,1,广东工业大学,False,U,3
4,CN107123117B,1,广东工业大学,False,U,3
...,...,...,...,...,...,...
169262,CN107530878B,1,整形工具股份有限公司,False,E,2
169263,CN109035141B,1,上海皓桦科技股份有限公司,False,E,2
169264,CN110363075B,1,南京特殊教育师范学院,False,U,3
169265,CN113313701B,1,兰州智悦信息科技有限公司,False,E,2
169266,CN115797335B,1,武汉地震工程研究院有限公司,True,E,2

In [90]:
cited_data = read_data[['cited_no','cited_assignee_pure']]
cited_data

            cited_no cited_assignee_pure
0       CN105260710B            北京石油化工学院
1       CN105224430B      艾德克斯电子（南京）有限公司
2       CN105245362B     河南工业大学;西安电子科技大学
3       CN105234938B           精工爱普生株式会社
4       CN105234938B           精工爱普生株式会社
...              ...                 ...
153818  CN111709925B        深圳科亚医疗科技有限公司
153819  CN111709925B        深圳科亚医疗科技有限公司
153820  CN111709925B        深圳科亚医疗科技有限公司
153821  CN107449874B     中国科学院地理科学与资源研究所
153822  CN107127755B              华南理工大学

[153823 rows x 2 columns]

In [93]:
cited_temp = []
for index in cited_data.index:
    citing_no,assignees = cited_data.iloc[index]['cited_no'],cited_data.iloc[index]['cited_assignee_pure']
    split_assignees = assignees.split(";")
    combine_flag = True if len(split_assignees)>1 else False
    for i in range(len(split_assignees)):
        cited_temp.append({"citing":citing_no,"order":i+1,"cited_assignee":split_assignees[i],"is_combine":combine_flag})

In [96]:
cited_df = pd.DataFrame(cited_temp)
cited_df

              citing  order   cited_assignee  is_combine
0       CN105260710B      1         北京石油化工学院       False
1       CN105224430B      1   艾德克斯电子（南京）有限公司       False
2       CN105245362B      1           河南工业大学        True
3       CN105245362B      2         西安电子科技大学        True
4       CN105234938B      1        精工爱普生株式会社       False
...              ...    ...              ...         ...
168817  CN111709925B      1     深圳科亚医疗科技有限公司       False
168818  CN111709925B      1     深圳科亚医疗科技有限公司       False
168819  CN111709925B      1     深圳科亚医疗科技有限公司       False
168820  CN107449874B      1  中国科学院地理科学与资源研究所       False
168821  CN107127755B      1           华南理工大学       False

[168822 rows x 4 columns]

In [98]:
type_data.columns = ['cited_assignee','Assignee_type','Assignee_score']

In [99]:

cited_merge = pd.merge(cited_df,type_data,on='cited_assignee')
cited_merge

,citing,order,cited_assignee,is_combine,Assignee_type,Assignee_score
0,CN105260710B,1,北京石油化工学院,False,U,3
1,CN105260709B,1,北京石油化工学院,False,U,3
2,CN110171000B,1,北京石油化工学院,True,U,3
3,CN109741306B,1,北京石油化工学院,False,U,3
4,CN109741306B,1,北京石油化工学院,False,U,3
...,...,...,...,...,...,...
169392,CN111398529B,1,株式会社而摩比特,False,E,2
169393,CN110139730B,1,卡耐基梅隆大学,False,U,3
169394,CN108471946B,1,珀迪迈垂克斯公司,False,E,2
169395,CN111366684B,1,上海兆莹自控设备有限公司,False,E,2
169396,CN109961430B,2,国网吉林省电力有限公司超高压公司,True,E,2

In [100]:
citing_merge.columns = ['citing','order','cited_assignee','is_combine','Assignee_type','Assignee_score']

In [101]:
concat_df = pd.concat([citing_merge,cited_merge])
concat_df

,citing,order,cited_assignee,is_combine,Assignee_type,Assignee_score
0,CN105844614B,1,广东工业大学,False,U,3
1,CN109492546B,1,广东工业大学,False,U,3
2,CN107443373B,1,广东工业大学,False,U,3
3,CN106041932B,1,广东工业大学,False,U,3
4,CN107123117B,1,广东工业大学,False,U,3
...,...,...,...,...,...,...
169392,CN111398529B,1,株式会社而摩比特,False,E,2
169393,CN110139730B,1,卡耐基梅隆大学,False,U,3
169394,CN108471946B,1,珀迪迈垂克斯公司,False,E,2
169395,CN111366684B,1,上海兆莹自控设备有限公司,False,E,2
169396,CN109961430B,2,国网吉林省电力有限公司超高压公司,True,E,2

In [104]:
concat_df = concat_df.reset_index(drop=True)
concat_df

,citing,order,cited_assignee,is_combine,Assignee_type,Assignee_score
0,CN105844614B,1,广东工业大学,False,U,3
1,CN109492546B,1,广东工业大学,False,U,3
2,CN107443373B,1,广东工业大学,False,U,3
3,CN106041932B,1,广东工业大学,False,U,3
4,CN107123117B,1,广东工业大学,False,U,3
...,...,...,...,...,...,...
338659,CN111398529B,1,株式会社而摩比特,False,E,2
338660,CN110139730B,1,卡耐基梅隆大学,False,U,3
338661,CN108471946B,1,珀迪迈垂克斯公司,False,E,2
338662,CN111366684B,1,上海兆莹自控设备有限公司,False,E,2
338663,CN109961430B,2,国网吉林省电力有限公司超高压公司,True,E,2

In [105]:
concat_df.to_excel("./results/edge_belong.xlsx",index=None)

In [151]:
# 
read_data = pd.read_excel("./results/edge_belong.xlsx")
read_data

,citing,citing_assignees,cited,cited_assignees,citing_year
0,CN105844614B,广东工业大学,CN105260710B,北京石油化工学院,2016
1,CN112214368B,英业达科技有限公司;英业达股份有限公司,CN105224430B,艾德克斯电子（南京）有限公司,2020
2,CN112910720B,成都云智天下科技股份有限公司,CN105245362B,河南工业大学;西安电子科技大学,2021
3,CN104608125B,精工爱普生株式会社,CN105234938B,精工爱普生株式会社,2013
4,CN106239505B,广东电网有限责任公司电力科学研究院,CN105234938B,精工爱普生株式会社,2016
...,...,...,...,...,...
98263,CN113205509B,山东省人工智能研究院;齐鲁工业大学,CN111709925B,深圳科亚医疗科技有限公司,2021
98264,CN115272165B,推想医疗科技股份有限公司,CN111709925B,深圳科亚医疗科技有限公司,2022
98265,CN115222665B,浙江医准智能科技有限公司,CN111709925B,深圳科亚医疗科技有限公司,2022
98266,CN110596328B,北京机械设备研究所,CN107449874B,中国科学院地理科学与资源研究所,2019
98267,CN110355755B,深圳铭杰医疗科技有限公司,CN107127755B,华南理工大学,2018

In [139]:
citing_data = read_data[['citing','citing_assignees']]
citing_temp = []
for index in citing_data.index:
    citing_no,assignees = citing_data.iloc[index]['citing'],citing_data.iloc[index]['citing_assignees']
    split_assignees = assignees.split(";")
    combine_flag = True if len(split_assignees)>1 else False
    for i in range(len(split_assignees)):
        citing_temp.append({"citing":citing_no,"order":i+1,"cited_assignee":split_assignees[i],"is_combine":combine_flag})

In [140]:
citing_df = pd.DataFrame(citing_temp)
citing_df

              citing  order  cited_assignee  is_combine
0       CN105844614B      1          广东工业大学       False
1       CN112214368B      1       英业达科技有限公司        True
2       CN112214368B      2       英业达股份有限公司        True
3       CN112910720B      1  成都云智天下科技股份有限公司       False
4       CN104608125B      1       精工爱普生株式会社       False
...              ...    ...             ...         ...
107776  CN113205509B      2          齐鲁工业大学        True
107777  CN115272165B      1    推想医疗科技股份有限公司       False
107778  CN115222665B      1    浙江医准智能科技有限公司       False
107779  CN110596328B      1       北京机械设备研究所       False
107780  CN110355755B      1    深圳铭杰医疗科技有限公司       False

[107781 rows x 4 columns]

In [144]:
cited_data = read_data[['cited','cited_assignees']]
cited_temp = []
for index in cited_data.index:
    cited_no,assignees = cited_data.iloc[index]['cited'],cited_data.iloc[index]['cited_assignees']
    split_assignees = assignees.split(";")
    combine_flag = True if len(split_assignees)>1 else False
    for i in range(len(split_assignees)):
        cited_temp.append({"citing":cited_no,"order":i+1,"cited_assignee":split_assignees[i],"is_combine":combine_flag})

In [145]:
cited_df = pd.DataFrame(cited_temp)
cited_df

              citing  order   cited_assignee  is_combine
0       CN105260710B      1         北京石油化工学院       False
1       CN105224430B      1   艾德克斯电子（南京）有限公司       False
2       CN105245362B      1           河南工业大学        True
3       CN105245362B      2         西安电子科技大学        True
4       CN105234938B      1        精工爱普生株式会社       False
...              ...    ...              ...         ...
107806  CN111709925B      1     深圳科亚医疗科技有限公司       False
107807  CN111709925B      1     深圳科亚医疗科技有限公司       False
107808  CN111709925B      1     深圳科亚医疗科技有限公司       False
107809  CN107449874B      1  中国科学院地理科学与资源研究所       False
107810  CN107127755B      1           华南理工大学       False

[107811 rows x 4 columns]

In [146]:
concat_df = pd.concat([citing_df,cited_df])
concat_df = concat_df.reset_index(drop=True)
concat_df

              citing  order   cited_assignee  is_combine
0       CN105844614B      1           广东工业大学       False
1       CN112214368B      1        英业达科技有限公司        True
2       CN112214368B      2        英业达股份有限公司        True
3       CN112910720B      1   成都云智天下科技股份有限公司       False
4       CN104608125B      1        精工爱普生株式会社       False
...              ...    ...              ...         ...
215587  CN111709925B      1     深圳科亚医疗科技有限公司       False
215588  CN111709925B      1     深圳科亚医疗科技有限公司       False
215589  CN111709925B      1     深圳科亚医疗科技有限公司       False
215590  CN107449874B      1  中国科学院地理科学与资源研究所       False
215591  CN107127755B      1           华南理工大学       False

[215592 rows x 4 columns]

In [149]:

cited_merge = pd.merge(concat_df,type_data,on='cited_assignee',how='inner')
cited_merge

,citing,order,cited_assignee,is_combine,Assignee_type,Assignee_score
0,CN105844614B,1,广东工业大学,False,U,3
1,CN109492546B,1,广东工业大学,False,U,3
2,CN107443373B,1,广东工业大学,False,U,3
3,CN106041932B,1,广东工业大学,False,U,3
4,CN107123117B,1,广东工业大学,False,U,3
...,...,...,...,...,...,...
216277,CN110139730B,1,卡耐基梅隆大学,False,U,3
216278,CN108471946B,1,珀迪迈垂克斯公司,False,E,2
216279,CN110073404B,1,南坦生物组学有限责任公司,False,E,2
216280,CN110073404B,1,南坦生物组学有限责任公司,False,E,2
216281,CN111366684B,1,上海兆莹自控设备有限公司,False,E,2

In [150]:
concat_df.to_excel("./results/edge_belong2.xlsx",index=None)

In [152]:
read_data

,citing,citing_assignees,cited,cited_assignees,citing_year
0,CN105844614B,广东工业大学,CN105260710B,北京石油化工学院,2016
1,CN112214368B,英业达科技有限公司;英业达股份有限公司,CN105224430B,艾德克斯电子（南京）有限公司,2020
2,CN112910720B,成都云智天下科技股份有限公司,CN105245362B,河南工业大学;西安电子科技大学,2021
3,CN104608125B,精工爱普生株式会社,CN105234938B,精工爱普生株式会社,2013
4,CN106239505B,广东电网有限责任公司电力科学研究院,CN105234938B,精工爱普生株式会社,2016
...,...,...,...,...,...
98263,CN113205509B,山东省人工智能研究院;齐鲁工业大学,CN111709925B,深圳科亚医疗科技有限公司,2021
98264,CN115272165B,推想医疗科技股份有限公司,CN111709925B,深圳科亚医疗科技有限公司,2022
98265,CN115222665B,浙江医准智能科技有限公司,CN111709925B,深圳科亚医疗科技有限公司,2022
98266,CN110596328B,北京机械设备研究所,CN107449874B,中国科学院地理科学与资源研究所,2019
98267,CN110355755B,深圳铭杰医疗科技有限公司,CN107127755B,华南理工大学,2018

In [154]:

is_self = []
for index in read_data.index:
    flag = False
    citing_assignees,cited_assignees = read_data.iloc[index]['citing_assignees'],read_data.iloc[index]['cited_assignees']
    split_assignees = citing_assignees.split(";")
    for assignee in split_assignees:
        if assignee.strip() in cited_assignees:
            flag = True
            break
    is_self.append(flag)

In [156]:
read_data['is_self'] = is_self
read_data.to_excel("./results/edge_belong1.xlsx",index=None)